language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- pip install pydiatra $pyflakes
script:
- python3 -m pydiatra bitbucket-vanity
- python3 -m pyflakes bitbucket-vanity
- ./bitbucket-vanity jwilk

# vim:ts=2 sts=2 sw=2 et
